codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
comment:
  if: is_pull_request
report:
#  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
diff:
  if: is_pull_request
  datastores:
    - artifact://${GITHUB_REPOSITORY}
