name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint
        uses: reviewdog/action-golangci-lint@v2

      - name: Run tests
        uses: ./testdata/

      - name: Test TestUpload (1/2)
        uses: actions/download-artifact@v2
        with:
          name: TestUpload

      - name: Test TestUpload (2/2)
        run: cat artifact/testdata/test.txt

      - name: Test TestUploadLargeContent (1/2)
        uses: actions/download-artifact@v2
        with:
          name: TestUploadLargeContent

      - name: Test TestUploadLargeContent (2/2)
        uses: k1LoW/github-script-ruby@v2
        with:
          script: |
            File.open('artifact/testdata/large.txt') do |f|
              f.each_line do |line|
                unless line.match?(/^0123456789/)
                  puts line
                  exit 1
                end
              end
              unless f.lineno == 1024 * 1024 * 10
                puts f.lineno
                exit 1
              end
            end

      - name: Test TestUploadFiles (1/3)
        run: rm artifact/testdata/test2.txt artifact/testdata/test3.txt

      - name: Test TestUploadFiles (2/3)
        uses: actions/download-artifact@v2
        with:
          name: TestUploadFiles

      - name: Test TestUploadFiles (3/3)
        run: cat artifact/testdata/test2.txt artifact/testdata/test3.txt

      - name: Cleanup artifacts
        uses: glassechidna/artifact-cleaner@master
        with:
          minimumAge: 3600

      - name: Run octocov
        uses: k1LoW/octocov-action@v0

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
