name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint
        uses: reviewdog/action-golangci-lint@v2

      - name: Run tests
        uses: ./

      - name: Check TestUpload (1/2)
        uses: actions/download-artifact@v2
        with:
          name: TestUpload

      - name: Check TestUpload (2/2)
        run: cat artifact/testdata/test.txt

      - name: Check TestUploadFiles (1/3)
        run: rm artifact/testdata/test2.txt artifact/testdata/test3.txt

      - name: Check TestUploadFiles (2/3)
        uses: actions/download-artifact@v2
        with:
          name: TestUploadFiles

      - name: Check TestUploadFiles (3/3)
        run: cat artifact/testdata/test2.txt artifact/testdata/test3.txt

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
